### ISSUE TITLE
Failed at the contextify@0.1.15 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by edgar** [pattrn-project/pattrn#51]
Using:

- node v7.10.0
- npm 4.2.0

I'm getting the following error when I'm doing `npm install`:

```
$ npm install                                          

> contextify@0.1.15 install /Users/edgar/sandboxes/pattrn/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc:131:56: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                       ^
/Users/edgar/.node-gyp/7.10.0/include/node/v8.h:3662:52: note: 'NewInstance' has been explicitly marked
      deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                   ^
../src/contextify.cc:150:16: error: no member named 'SetAccessCheckCallbacks' in 'v8::ObjectTemplate'
        otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
        ~~~~~  ^
../src/contextify.cc:182:51: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                  ^
/Users/edgar/.node-gyp/7.10.0/include/node/v8.h:3234:30: note: 'GetRealNamedProperty' has been explicitly
      marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
../src/contextify.cc:209:38: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                     ^
/Users/edgar/.node-gyp/7.10.0/include/node/v8.h:3234:30: note: 'GetRealNamedProperty' has been explicitly
      marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
../src/contextify.cc:210:42: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
            !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                         ^
/Users/edgar/.node-gyp/7.10.0/include/node/v8.h:3234:30: note: 'GetRealNamedProperty' has been explicitly
      marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/edgar/sandboxes/pattrn/node_modules/contextify
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
pattrn@2.0.0 /Users/edgar/sandboxes/pattrn
└── (empty)

npm WARN grunt-gh-pages@1.1.0 requires a peer of grunt@>=0.4.0 but none was installed.
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/edgar/.npm/_logs/2017-05-06T01_17_50_554Z-debug.log
```

Are you guys using a different version of node/npm?

**Comment by hotzeplotz** [comment]
we are currently targeting Node LTS (so 6.10.3 at the moment).

i have created a [new branch with a Yarn lock file](https://github.com/pattrn-project/pattrn/tree/feature/yarn) which should also help to make sure the version you build is using the same exact dependencies as the one that builds correctly for me - does downgrading to Node LTS and/or building with `yarn install && yarn run gulp build` from the branch linked above work for you?

Yarn support will shortly be merged back into master.

**Comment by edgar** [comment]
Using Node LTS solved the issue, thanks

**Comment by hotzeplotz** [comment]
@edgar thanks for confirming. The issue you were running into seems to be an open bug in the `contextify` package (https://github.com/brianmcd/contextify/issues/211).

Indeed this fails on all Node 7 CI builds i have set up in my fork of Pattrn (e.g. https://travis-ci.org/hotzeplotz/pattrn/builds/229505228), so once this is fixed in `contextify` the Node 7 CI builds for Pattrn should go green again.

I will update the documentation on the next point release to advise users about this issue - thanks for your input.

**Comment by hotzeplotz** [comment]
@edgar i tracked down the `contextify`package as a dependency of a package that wasn't really needed for the current Pattrn release: this is now removed and you should be able to build Pattrn on Node 7 if you prefer to use this version (https://travis-ci.org/hotzeplotz/pattrn/builds/229517246 all green at last).

**Comment by edgar** [comment]
Great, thanks @hotzeplotz !

BTW I have a questions about how to specify media (photos, videos, links) in the geojson file, should I ask it in the google groups?

**Comment by hotzeplotz** [comment]
@edgar pleasure.

do hop on https://gitter.im/pattrn/community for queries.
